exports.AccessToken = require('./lib/access-token')
exports.BaseApi = require('./lib/base')
exports.WxWork = require('./lib/wx-work')
exports.WxWorkProvider = require('./lib/wx-work-provider')
exports.WxWorkSuite = require('./lib/wx-work-suite')
exports.Receiver = require('./lib/receiver')
exports.Wechat = require('./lib/wechat')
exports.WechatOauth = require('./lib/wechat-oauth')
Object.assign(exports, require('./lib/error'))
